version: '3.3'

services:
  mysql:
    image: docker.io/mysql:8
    restart: always
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: config-test
      MYSQL_USER: alice
      MYSQL_PASSWORD: foo
    ports:
      - 3306:3306

  postgres:
    image: docker.io/postgres:14
    restart: always
    environment:
      POSTGRES_DB: config-test
      POSTGRES_USER: alice
      POSTGRES_PASSWORD: foo
    ports:
      - "5432:5432"

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: passwordA1!
      MSSQL_PID: Developer
      MSSQL_TCP_PORT: 1433
    ports:
      - 1433:1433
